apiVersion: v2
name: radicale
description: A Helm chart for Radicale

type: application
version: 0.1.4
# renovate: image=tomsquest/docker-radicale
appVersion: "3.7.1.0"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.0
