{{/* Preprocess values and prepare config file */}}
{{- define "feishin.preprocess" -}}
service:
  http:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 9180

controllers:
  main:
    replicas: {{ .Values.replicas }}
    containers:
      main:
        image:
          {{- toYaml .Values.image | nindent 10 }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
{{- end -}}
{{- $_ := merge .Values (include "feishin.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
