{{/* Preprocess values and prepare config file */}}
{{- define "feishin.preprocess" -}}
controllers:
  feishin:
    replicas: {{ .Values.replicas }}
    containers:
      feishin:
        image:
          {{- toYaml .Values.image | nindent 10 }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        {{ with .Values.probes }}
        probes:
          {{ toYaml . | nindent 10 }}
        {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "feishin.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
