#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
# # -- image repository
  repository: ghcr.io/juniorjpdj/ziprofs
# # -- image pull policy
  pullPolicy: IfNotPresent
# # -- image tag
  tag: latest@sha256:6c795630633afdaf6cc53e1c7f4ac277c17c80df3f61a4166e8d3e18d9654821


args:
# -- Override default command(s) to run
  - /app/root
  - /app/mnt
  - -o
  - allowother,foreground,async,cachesize=3000

persistence:
# # -- Input mount, which will be used to mount the source directory
  input:
    accessMode: ReadOnlyMany
    size: 1Gi
    storageClass: external
    advancedMounts:
      main:
        main:
          - path: /app/root
            readOnly: true

# # -- Output mount, which will be used to mount the destination directory (e.g. ZipROFSed input)
  output:
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: external
    advancedMounts:
      main:
        main:
          - path: /app/mnt
            readOnly: false
