apiVersion: v2
name: navidrome
description: GoLang streaming service
type: application
version: 0.1.18
# renovate: image=ghcr.io/navidrome/navidrome
appVersion: 0.61.2
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.0
sources:
  - https://github.com/navidrome/navidrome
