#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
# # -- image repository
  repository: ghcr.io/juniorjpdj/tgmount
# # -- image pull policy
  pullPolicy: IfNotPresent
# # -- image tag
  tag: latest@sha256:6c2c532f430fa64f95066283b0e201b26ac5dda58bbf99a01aca34f09d896ab6

args:
# -- Override default command(s) to run
  []

secret:
  {}
# # TGAPP Options:
# # B) tgapp:
# #      tgapp: super_secret_tgapp_token
# # C) tgapp:
# #      existing_secret: super_secret_existing_tgapp_token_secret

persistence:
# # -- Output mount, which will be used to mount the chat to.
  chat:
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: external
    advancedMounts:
      main:
        main:
          - path: /app/data/mnt
            readOnly: false
            mountPropagation: Bidirectional

  tgsession:
    accessMode: ReadWriteOnce
    size: 200Mi
    storageClass: external
    advancedMounts:
      main:
        main:
          - path: /app/data
            readOnly: false
