apiVersion: v2
name: bewcloud
description: A Helm chart for BewCloud

type: application
version: 0.4.2
# renovate: image=ghcr.io/bewcloud/bewcloud
appVersion: "v4.5.1"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.0
  - name: radicale
    condition: radicale.enabled
    repository: oci://ghcr.io/loboda4450/charts
    version: 0.2.1
