{{/* Preprocess values and prepare config file */}}
{{- define "flaczkownia-dedup.preprocess" -}}
service:
  http:
    type: ClusterIP
    controller: connector
    ports:
      http:
        port: {{ .Values.connector.port }}

controllers:
  connector:
    type: statefulset
    replicas: {{ .Values.connector.replicas | default 1 }}
    defaultContainerOptions:
      args:
        - --base-dir
        - {{ .Values.connector.baseDir | quote }}
        - --db
        - {{ .Values.database | quote }}
        - --host
        - {{ .Values.connector.host | quote }}
        - --port
        - {{ .Values.connector.port | quote }}
        {{- if not (empty .Values.connector.viewMode) }}
        - --view-dir
        - {{ .Values.connector.viewDir | quote }}
        - --db-prefix
        - {{ .Values.connector.dbPrefix | quote }}
        {{- end }}
        {{- if eq .Values.connector.viewMode "symlink" }}
        - --source-relative-path
        - {{ required "sourceRelativePath is required with symlink view mode" .Values.connector.sourceRelativePath | quote }}
        {{- else if eq .Values.connector.viewMode "copy" }}
        - --source-path
        - {{ required "sourcePath is required with copy view mode" .Values.connector.sourcePath | quote }}
        {{- end }}
      command:
        - python
        - connector.py

    containers:
      connector:
        image:
          {{- toYaml .Values.connector.image | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

  dedup:
    type: deployment
    replicas: {{ .Values.dedup.replicas | default 1 }}
    defaultContainerOptions:
      args:
        - --db
        - {{ .Values.database | quote }}
        {{- if or (empty .Values.connector.webhookUrls) (eq (len .Values.connector.webhookUrls) 0)}}
        - --webhook-url
        - {{ printf "http://connector.%s.svc:%d/api/v1/dedup_processed_file_webhook" .Release.Namespace (int .Values.connector.port) | quote}}
        {{- else }}
        {{- range .Values.connector.webhookUrls }}
        - --webhook-url
        - {{ quote . }}
        {{- end }}
        {{- end }}

    containers:
      dedup:
        image:
          {{- toYaml .Values.dedup.image | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

persistence:
# # -- Mount to store the database
  database:
    enabled: {{ contains "sqlite" .Values.database }}
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      connector:
        connector:
          - path: /app/data
            readOnly: false
      dedup:
        dedup:
          - path: /app/data
            readOnly: false

  ziprofs:
# # -- Dedup input directory (ziprofs output)
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      dedup:
        dedup:
          - path: /app/data/music
            readOnly: true
      {{- if eq .Values.connector.viewMode "copy" }}
      connector:
        connector:
          - path: /app/data/music
            readOnly: true
      {{- end }}

  deduplicated:
# # -- Deduplicated view directory
    enabled: {{ not (empty .Values.connector.viewMode) }}
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      connector:
        connector:
          - path: /app/data/deduped
            readOnly: false

{{- end -}}
{{- $_ := merge .Values (include "flaczkownia-dedup.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
