apiVersion: v2
name: flaczkownia-dedup
description: A Helm chart for Flaczkownia Deduplication service

type: application
version: 0.1.1
appVersion: "latest"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
